steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/testproject-354013/github.com/vpedrota/actionstest:$SHORT_SHA', '.']
  
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/testproject-354013/github.com/vpedrota/actionstest:$SHORT_SHA']

- name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta', 'run', 'deploy', 'actiontest', '--region=us-central1', '--platform=managed' ,'--image=gcr.io/testproject-354013/github.com/vpedrota/actionstest:$SHORT_SHA']

